{{- if .Values.sidecar.storage.enabled  -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "desktop-sidecar.pvc-name" . }}
spec:
  accessModes:
  {{- range $key, $val := .Values.sidecar.storage.accessModes }}
    {{ if $val }}
      - {{ $key }}
    {{ end }}
  {{ end -}}
  resources:
    requests:
      storage: {{ .Values.sidecar.storage.size }}
  storageClassName: {{ .Values.sidecar.storage.storageClass }}
  volumeMode: Filesystem
{{- end -}}